### ISSUE TITLE
Unable to disable modules

### ISSUE THREAD

**Issue by Ryuco** [iron431/rpg-tweaks#11]
I've been trying to remove the hunger and durability modules and no matter what i do they refuse to turn off, i have no idea why but it has never worked even without other mods so Im wondering if that's a known problem

**Comment by Ryuco** [comment]
for reference it puts the hunger bar back up when turned off, however it keeps all of the same mechanics and is very annoying.

**Comment by Ryuco** [comment]
they also reapply if my server restarts

**Comment by Bearytiss** [comment]
I also have this issue. Can't disable either of those modules.

**Comment by iron431** [comment]
edit the configs with the server closed, and verify there are no typos in the config
