### ISSUE TITLE
[Feature Request] Config option for the exp death orb to hold dropped items too

### ISSUE THREAD

**Issue by OHKOBunny** [iron431/rpg-tweaks#16]
This would be my favorite death inventory management mod if you could include this, but given how volatile and buggy even the already established ones can be, I'd totally understand not wanting the hassle.

However running this with corpse makes it a bit cluttered when returning to your death spot since you have both a grave and an obelisk to interact with, and I personally would rather just have the orb hold stuff.

Please consider it!

**Comment by iron431** [comment]
This will not be worked on, corpse is exactly how I would do it.
