### ISSUE TITLE
Purple-Black Armor [Bug]

### ISSUE THREAD

**Issue by CrowMage** [iron431/rpg-tweaks#17]
**What's problem Doc?**

**Iron's Spells and Spellbooks armor** turning into a **_Purple-Black_** armor(but Netherite Battlemage armor transforming into a normal Netherite armor).
**Screenshot:**
![image](https://github.com/iron431/rpg-tweaks/assets/162807007/08c51870-7786-4afb-bf84-28fdb0b32bfb)
**Version:**
_1.20.1 Forge(47.2.20)_

**Comment by iron431** [comment]
1) wrong mod
2) read the faq
