### ISSUE TITLE
Issue with PlayerRevive preventing the gear from taking damage

### ISSUE THREAD

**Issue by CreativeMD** [iron431/rpg-tweaks#19]
Hey there,
I'm the author of PlayerRevive. Seems like there is an issue with gears taking damage: https://github.com/CreativeMD/PlayerRevive/issues/150

If a player dies PlayerRevive cancels the event and makes the player enter a bleeding state. In that state the player can access their inventory and drop their gear to bypass the penalty. I think the best solution would be if the gear is damaged as soon as the player enters the bleeding state. Is there a method PlayerRevive can tell to initiate the damage of the tools? Furthermore maybe you can add a check if PlayerRevive is installed to prevent the gear taken damage when the player bleeds out.

In Regards
CreativeMD

**Comment by iron431** [comment]
if you want to change the behavior of my mod, then make an addon. rpg tweaks is mostly sunset for now anyways
https://github.com/iron431/rpg-tweaks/blob/1.19.2/src/main/java/io/redspace/ironsrpgtweaks/durability_module/DurabilityServerEvents.java#L47
