### ISSUE TITLE
[1.20.1] Mod breaks the SlashBlade Resharped mod.

### ISSUE THREAD

**Issue by cfnnit** [iron431/rpg-tweaks#23]
When using the SlashBlade mod together with RPG Tweak, an issue arises where the katanas from SlashBlade fail to deal damage properly.

I suspected the issue might be related to the damage module, so I disabled the damage module in the settings. 
However, the problem still persists.

https://youtu.be/OkQsI16D2lw?si=_rSP4brLHJFWCkPm

**Comment by iron431** [comment]
try changing the minimum attack strength

**Comment by cfnnit** [comment]
> try changing the minimum attack strength

Adjusting the value closer to 0 resolved the issue. Thank you!
