### ISSUE TITLE
identification_scroll texture breaking mipmap levels

### ISSUE THREAD

**Issue by Fannalol** [iron431/rpg-tweaks#25]
Hello Iron, could you fix this? Unfortunately using a textures with dimensions that aren't the power of 2 will completely disable mipmap levels, resulting in the game looking weird and grainy. `irons_rpg_tweaks-1.20-1.2.4.jar`

[Worker-ResourceReload-5/WARN]: Texture irons_rpg_tweaks:item/identification_scroll with size 15x14 limits mip level from 4 to 0

**Comment by iron431** [comment]
not sure how that managed to slip in, fixed in 1.2.5
