### ISSUE TITLE
Bug crashing World

### ISSUE THREAD

**Issue by WilliamBlaze** [iron431/rpg-tweaks#3]
The full details and mod list are in the link below, which should make reading the crash log a bit more legible. -- All I understood from any of it is it has something to do with the Debug feature from RPG Tweaks, and alot of other details i couldn't make sense of.

https://pastebin.com/gr7cUjpb

**Comment by iron431** [comment]
Do you have debug mode turned on?

**Comment by WilliamBlaze** [comment]
i did at the time because i was testing a mod pack i'm building - specifically i was trying to see if certain features from Mahou Tsukai would still work given the way RPG Tweaks handles i-frames and how that effects certain entity ticking

**Comment by iron431** [comment]
This will be fixed in the next version
